[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000
maxUploadSize = 250
fileWatcherType = "none"

[global]
disableWatchdogWarning = true
sharingMode = "off"

[runner]
fastReruns = false
